### ISSUE TITLE
Homebrew support?

### ISSUE THREAD

**Issue by Olshansk** [MilesCranmer/rip2#62]
Do you have any plans on making this accessible/installable via homebrew?

Might be something I can help with but want to avoid duplicate effort first.

**Comment by MilesCranmer** [comment]
Thanks for the interest. I don’t have bandwidth to maintain each package repository myself other than cargo and flake but if you are up for taking it on, I’d be happy to advertise

**Comment by chenrui333** [comment]
fyi, there is an open PR for it, https://github.com/Homebrew/homebrew-core/pull/196052

**Comment by chenrui333** [comment]
@MilesCranmer I am thinking to migrate the existing rm-improved to rip2, but I see two issues

- rip in cargo registry is called rm-improved, while rip2 is called rip2 (no naming consistency)
- the last rip release is 0.13.1, while rip2 is 0.9.0 (actually version downgrade)

can you have a chance of maybe addressing both of them? Thanks!

**Comment by MilesCranmer** [comment]
> rip in cargo registry is called rm-improved, while rip2 is called rip2 (no naming consistency)

My guess is that the original was put into a crate labeled `rm-improved` rather than `rip` because there was already a `rip` (someone's random test package took the rip name: https://crates.io/crates/rip). My guess is that the original creator of rip would have preferred to label it as rip in the registry... who knows though. For rip2 I thought it made more sense over `rm-improved2` which is a bit verbose, and is semantically like "rm_improved_improved". So I preferred to just call it "rip2" and avoid keeping the original backronym.

> the last rip release is 0.13.1, while rip2 is 0.9.0

I can't push to the original rip's package repositories so I thought it made more sense to restart at 0.1.0.

However I can see this might cause issues if treating rip2 as an alias to rip.

What would you suggest? Perhaps I should re-release 0.9.0 of rip2 as 0.14.0? Then I suppose would meet SemVer requirements, and someone could simply upgrade from `rip@0.13.1` to `rip@0.14.0` and it would be equivalent. I feel like that's the easiest solution.

**Comment by MilesCranmer** [comment]
However I think the "proper" way to do things is to have a separate `rip2` package in brew, and leave `rip` as is. This is also what termux did: https://github.com/termux/termux-packages/pull/21922

**Comment by bkaplowitz** [comment]
Should now be merged into homebrew as rip2.

**Comment by MilesCranmer** [comment]
Awesome! I mentioned it on the readme. Many thanks @bkaplowitz.
